version: '3.9'

services:
  postgres-db:
    image: postgres:16.3
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=03212164
      - POSTGRES_DB=personal_finance_tracker
    volumes:
      - postgres-data:/data/postgres
    ports:
      - 5434:5432
    networks:
      - finance_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 29092:29092
    networks:
      - finance_net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - 22181:2181
    networks:
      - finance_net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6378:6379
    networks:
      - finance_net

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27018:27017
    networks:
      - finance_net
    volumes:
      - mongo_data:/data/db

  api_app:
    build: .
    container_name: api_app
    depends_on:
      postgres-db:
        condition: service_started
      kafka:
        condition: server_healthy
    ports:
      - 8080:9999
    networks:
      - finance_net

networks:
  finance_net:
    external: true
    name: finance_net
    driver: bridge

volumes:
  postgres-data:
  mongo_data:
